name: CD

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  test_and_build:
    uses: ./.github/actions/build-and-test.yml

  deploy:
    name: 🚀 Deploy
    needs: [test_and_build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          clean: true
