name: CI

on:
  push:
    branches:
      - develop
      - feature/*
      - hotfix/*

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:ci

      - name: Build
        run: yarn build

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build

  lighthouse:
    name: Lighthouse
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: web
          path: build

      - name: Install and run Lighthouse
        run: |
          yarn global add @lhci/cli
          lhci autorun
